<#
Minimal PowerShell profile entrypoint.

Do not edit this file unless you understand what it does.

This script loads (dot-sources) every `*.ps1` in the sibling `fns\` folder.
#>

# Prevent accidental double-loading (e.g. if `main.ps1` is dot-sourced twice).
# Uses $global: to stay compatible with very old PowerShell versions.
if ($global:__LightProfileLoaded) { return }
$global:__LightProfileLoaded = $true

function Get-ProfileScriptRoot {
    if (Get-Variable -Name PSScriptRoot -ErrorAction SilentlyContinue) {
        if ($PSScriptRoot) { return $PSScriptRoot }
    }

    if ($MyInvocation -and $MyInvocation.MyCommand -and $MyInvocation.MyCommand.Path) {
        return (Split-Path -Parent $MyInvocation.MyCommand.Path)
    }

    return (Get-Location).Path
}

$profileRoot = Get-ProfileScriptRoot
$fnsDir = Join-Path $profileRoot 'fns'

# Load every `*.ps1` from `fns\` (if it exists).
if (Test-Path -Path $fnsDir) {
    $fnsScripts = Get-ChildItem -Path $fnsDir -ErrorAction SilentlyContinue |
        Where-Object { -not $_.PSIsContainer -and $_.Name -like '*.ps1' } |
        Sort-Object -Property Name

    foreach ($fnsScript in $fnsScripts) {
        try {
            . $fnsScript.FullName
        }
        catch {
            Write-Warning ("Failed to load: {0} ({1})" -f $fnsScript.FullName, $_.Exception.Message)
        }
    }

    Remove-Variable fnsScripts, fnsScript -ErrorAction SilentlyContinue
}

Remove-Variable profileRoot, fnsDir -ErrorAction SilentlyContinue

