<#
Minimal PowerShell profile entrypoint.

Do not edit this file unless you understand what it does.

This script loads (dot-sources) every `*.ps1` in the sibling `fns\` folder.
#>

# Prevent accidental double-loading (e.g. if `main.ps1` is dot-sourced twice).
# Uses $global: to stay compatible with very old PowerShell versions.
if ($global:__LightProfileLoaded) { return }
$global:__LightProfileLoaded = $true

function Get-ProfileScriptRoot {
    if (Get-Variable -Name PSScriptRoot -ErrorAction SilentlyContinue) {
        if ($PSScriptRoot) { return $PSScriptRoot }
    }

    if ($MyInvocation -and $MyInvocation.MyCommand -and $MyInvocation.MyCommand.Path) {
        return (Split-Path -Parent $MyInvocation.MyCommand.Path)
    }

    return (Get-Location).Path
}

$profileRoot = Get-ProfileScriptRoot
$fnsDir = Join-Path $profileRoot 'fns'
$configPath = Join-Path $profileRoot 'config.toml'
$repoPath = Join-Path $profileRoot '.nexshell_repo'

# Load every `*.ps1` from `fns\` (if it exists).
if (Test-Path -Path $fnsDir) {
    $fnsScripts = Get-ChildItem -Path $fnsDir -ErrorAction SilentlyContinue |
        Where-Object { -not $_.PSIsContainer -and $_.Name -like '*.ps1' } |
        Sort-Object -Property Name

    foreach ($fnsScript in $fnsScripts) {
        if ($fnsScript.Name -eq 'ls_icons.ps1' -and -not $enabledNerdIcons) { continue }
        try {
            . $fnsScript.FullName
        }
        catch {
            Write-Warning ("failed to load: {0} ({1})" -f $fnsScript.FullName, $_.Exception.Message)
        }
    }

    Remove-Variable fnsScripts, fnsScript -ErrorAction SilentlyContinue
}

$deprecatedCheckPath = Join-Path $profileRoot 'deprecated_check.ps1'
if (Test-Path -Path $deprecatedCheckPath) {
    try { . $deprecatedCheckPath } catch { }
}

function Get-EnabledNerdIcons {
    param([Parameter(Mandatory = $true)][string] $Path)

    $defaultValue = $false

    try {
        if (-not (Test-Path -Path $Path)) { return $defaultValue }
    }
    catch {
        return $defaultValue
    }

    try {
        $lines = Get-Content -Path $Path -ErrorAction Stop
    }
    catch {
        return $defaultValue
    }

    foreach ($line in @($lines)) {
        if ($null -eq $line) { continue }
        $m = [Regex]::Match(
            $line,
            '^\s*enabled_nerd_icons\s*=\s*(true|false)\s*(#.*)?$',
            [System.Text.RegularExpressions.RegexOptions]::IgnoreCase
        )
        if ($m.Success) {
            return [bool]::Parse($m.Groups[1].Value.ToLower())
        }
    }

    return $defaultValue
}

$updateChannel = Get-UpdateChannel -Path $configPath
Set-Variable -Name updateChannel -Value $updateChannel -Scope Global -Force

$enabledNerdIcons = Get-EnabledNerdIcons -Path $configPath
Set-Variable -Name enabledNerdIcons -Value $enabledNerdIcons -Scope Global -Force

Remove-Variable profileRoot, fnsDir, configPath, repoPath -ErrorAction SilentlyContinue
