<#
Minimal PowerShell profile entrypoint.

Do not edit this file unless you understand what it does.

This script loads (dot-sources) every `*.ps1` in the sibling `fns\` folder.
#>

# Prevent accidental double-loading (e.g. if `main.ps1` is dot-sourced twice).
# Uses $global: to stay compatible with very old PowerShell versions.
if ($global:__LightProfileLoaded) { return }
$global:__LightProfileLoaded = $true

function Get-ProfileScriptRoot {
    if (Get-Variable -Name PSScriptRoot -ErrorAction SilentlyContinue) {
        if ($PSScriptRoot) { return $PSScriptRoot }
    }

    if ($MyInvocation -and $MyInvocation.MyCommand -and $MyInvocation.MyCommand.Path) {
        return (Split-Path -Parent $MyInvocation.MyCommand.Path)
    }

    return (Get-Location).Path
}

$profileRoot = Get-ProfileScriptRoot
$fnsDir = Join-Path $profileRoot 'fns'
$configPath = Join-Path $profileRoot 'config.toml'
$repoPath = Join-Path $profileRoot '.nexshell_repo'

# Load every `*.ps1` from `fns\` (if it exists).
if (Test-Path -Path $fnsDir) {
    $fnsScripts = Get-ChildItem -Path $fnsDir -ErrorAction SilentlyContinue |
        Where-Object { -not $_.PSIsContainer -and $_.Name -like '*.ps1' } |
        Sort-Object -Property Name

    foreach ($fnsScript in $fnsScripts) {
        try {
            . $fnsScript.FullName
        }
        catch {
            Write-Warning ("Failed to load: {0} ({1})" -f $fnsScript.FullName, $_.Exception.Message)
        }
    }

    Remove-Variable fnsScripts, fnsScript -ErrorAction SilentlyContinue
}

function Get-AutoUpdate {
    param([Parameter(Mandatory = $true)][string] $Path)

    $defaultValue = $true

    try {
        if (-not (Test-Path -Path $Path)) {
            "auto_update = true`r`n" | Set-Content -Path $Path -Encoding UTF8 -Force
            return $defaultValue
        }
    }
    catch {
        return $defaultValue
    }

    try {
        $lines = Get-Content -Path $Path -ErrorAction Stop
    }
    catch {
        return $defaultValue
    }

    foreach ($line in @($lines)) {
        if ($null -eq $line) { continue }
        $m = [Regex]::Match(
            $line,
            '^\s*auto_update\s*=\s*(true|false)\s*(#.*)?$',
            [System.Text.RegularExpressions.RegexOptions]::IgnoreCase
        )
        if ($m.Success) {
            return ($m.Groups[1].Value.ToLower() -eq 'true')
        }
    }

    return $defaultValue
}

$autoUpdate = Get-AutoUpdate -Path $configPath
if ($autoUpdate) {
    # Avoid noisy errors on startup when updates aren't configured yet.
    $hasRepo = $false
    try {
        if ($env:NEXSHELL_REPO) { $hasRepo = $true }
        elseif (Test-Path -Path $repoPath) { $hasRepo = $true }
    }
    catch {
        $hasRepo = $false
    }

    if ($hasRepo) {
        try {
            if (Get-Command -Name 'upd' -ErrorAction SilentlyContinue) {
                upd
            }
        }
        catch {
            # Do not block shell startup on updater errors.
            Write-Warning ("Auto-update failed: {0}" -f $_.Exception.Message)
        }
    }

    Remove-Variable hasRepo -ErrorAction SilentlyContinue
}

Remove-Variable autoUpdate -ErrorAction SilentlyContinue
Remove-Item -Path Function:Get-AutoUpdate -ErrorAction SilentlyContinue
Remove-Variable profileRoot, fnsDir, configPath, repoPath -ErrorAction SilentlyContinue
