<#
Minimal PowerShell profile (Windows PowerShell + PowerShell 7+).

Do not edit this file unless you understand what it does.

This profile only loads (dot-sources) every `*.ps1` in the sibling `fns\`
folder next to this file.
#>

# Prevent accidental double-loading (e.g. if the profile is dot-sourced).
# Uses $global: (available in very old PowerShell versions) to avoid relying
# on cmdlet parameters that may not exist in v1/v2.
if ($global:__LightProfileLoaded) { return }
$global:__LightProfileLoaded = $true

function Get-ProfileScriptRoot {
    if (Get-Variable -Name PSScriptRoot -ErrorAction SilentlyContinue) {
        if ($PSScriptRoot) { return $PSScriptRoot }
    }

    if ($MyInvocation -and $MyInvocation.MyCommand -and $MyInvocation.MyCommand.Path) {
        return (Split-Path -Parent $MyInvocation.MyCommand.Path)
    }

    # Last-resort fallback (shouldn't happen for a normal profile load).
    return (Get-Location).Path
}

$profileRoot = Get-ProfileScriptRoot
$fnsDir = Join-Path $profileRoot 'fns'

# Load every `*.ps1` from `fns\` (if it exists).
if (Test-Path -Path $fnsDir) {
    $fnsScripts = Get-ChildItem -Path $fnsDir -ErrorAction SilentlyContinue |
        Where-Object { -not $_.PSIsContainer -and $_.Name -like '*.ps1' } |
        Sort-Object -Property Name

    foreach ($fnsScript in $fnsScripts) {
        try {
            . $fnsScript.FullName
        }
        catch {
            Write-Warning ("Failed to load: {0} ({1})" -f $fnsScript.FullName, $_.Exception.Message)
        }
    }

    Remove-Variable fnsScripts, fnsScript -ErrorAction SilentlyContinue
}

Remove-Variable profileRoot, fnsDir -ErrorAction SilentlyContinue
