<#
PowerShell profile shim.

Do not edit this file unless you understand what it does.

This file only dot-sources `main.ps1` (keeps the actual logic in one place).
#>

$profileRoot = $null
try { $profileRoot = $PSScriptRoot } catch { $profileRoot = $null }
if (-not $profileRoot) {
    try {
        if ($MyInvocation -and $MyInvocation.MyCommand -and $MyInvocation.MyCommand.Path) {
            $profileRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
        }
    }
    catch {
        $profileRoot = $null
    }
}
if (-not $profileRoot) { $profileRoot = (Get-Location).Path }

$main = $null
try { $main = Join-Path $profileRoot 'main.ps1' } catch { $main = $null }

if ($main -and (Test-Path -Path $main)) {
    . $main
}
else {
    Write-Warning ("Profile entrypoint not found: {0}" -f $main)
}

Remove-Variable profileRoot, main -ErrorAction SilentlyContinue
